apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools-custom
  namespace: openshift-storage
  labels:
    app: rook-ceph-tools-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools-custom
  template:
    metadata:
      labels:
        app: rook-ceph-tools-custom
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: rook-ceph-tools-custom
          securityContext:
            runAsUser: 0
          image: registry.redhat.io/odf4/rook-ceph-rhel8-operator@sha256:671d29d8af48e266d1c824985eab9d01e8d2ddd7cb640190bf0f9f7a26d41a91
          command: ["/bin/bash"]
          args: ["-m", "-c", "/usr/local/bin/toolbox.sh"]
          imagePullPolicy: IfNotPresent
          tty: true
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-secret
          volumeMounts:
            - mountPath: /etc/ceph
              name: ceph-config
            - name: mon-endpoint-volume
              mountPath: /etc/rook
      volumes:
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
              - key: data
                path: mon-endpoints
        - name: ceph-config
          emptyDir: {}
      tolerations:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
