---
# https://github.com/RedHatOfficial/ocp4-vsphere-upi-automation/blob/master/roles/vsphere_vm/tasks/static-iso.yml#L89
# https://github.com/sa-ne/openshift4-vmware-upi/blob/514ca0174c840c8ad664d96cefe3f8fbb582d7db/roles/vmware/tasks/vms-cluster-placement.yaml#L6
# This is not idempotent! It fails with error:
#   "op: reconfig"
#   "msg: A specified parameter was not correct: spec.cpuAllocation"
- name: Create a virtual machine
  community.vmware.vmware_guest:
    folder: "{{ vsphere.vm_folder }}"
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    cluster: "{{ vsphere.cluster_name }}"
    datacenter: "{{ vsphere.datacenter_name }}"
    name: "{{ __vm.hostname }}"
    state: poweredon
    guest_id: rhel8_64Guest
    validate_certs: false
    advanced_settings:
    - key: disk.EnableUUID
      value: 'TRUE'
    - key: stealclock.enable
      value: 'TRUE'
      #- key: sched.cpu.latencySensitivity
      #value: 'High'
    disk: "{{ __vm.disks }}"
    hardware:
      memory_mb: "{{ __vm.ram }}"
      memory_reservation_lock: true
      hotadd_memory: false
      num_cpus: "{{ __vm.cpu }}"
      #cpu_reservation: 18400
      hotadd_cpu: false
      hotremove_cpu: false
      version: "{{ vsphere.hwversion }}"
      boot_firmware: "efi"
    cdrom:
      - controller_number: 0
        unit_number: 0
        type: iso
        iso_path: "[{{ vsphere.datastore_name }}] {{ vsphere.datastore_iso_folder }}/{{ agent_iso_name }}"
        state: present
    networks:
    - name: "{{ vsphere.network_name }}"
      type: static
      start_connected: true
      mac: "{{ __vm.nic_mac }}"
  loop: "{{ vm_definition }}"
  loop_control:
    loop_var: __vm
  async: 1000
  poll: 0
  register: vm_sleeper

- name: Check on an async task
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 200
  delay: 10
  loop: "{{ vm_sleeper.results }}"
...
