---
# tasks file for install-vsphere

- name: Upload ISO to vSphere
  import_tasks: upload-iso-vsphere.yaml
  tags:
  - upload-iso

- name: Deploy cluster in vSphere from ISO
  import_tasks: boot_vm_fromiso.yaml
  tags:
  - deploy
...
