---
- name: Encrypt etcd
  ansible.builtin.import_tasks:
    file: encrypt_etcd.yaml
  when: ocp_encrypt_etcd | bool == true

# tasks file for day2_openshift
- name: Find all manifest templates
  ansible.builtin.find:
   paths: "{{ role_path }}/templates/openshift_manifests/"
  register: manifest_files

- name: Apply openshift manifests
  redhat.openshift.k8s:
    template: "{{ item.path }}"
    kubeconfig: "{{ installation_path }}/auth/kubeconfig"
  loop: "{{ manifest_files.files }}"
...
