---
vsphere:
  hostname: portal.vc.opentlc.com
  username: sandbox-pm2pn@vc.opentlc.com
  password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65633864643537656230383437653533656661313162326235633536333536356537323061303162
          3563633965633235376539663335346561663463336535630a383833633464626335666562656661
          61326430386632333264366366316534333235613265333763326163346539386265386161373232
          3537356562626131610a356233323930386563656438646338316439626236326665366266646538
          6338
  datastore_name: "WorkloadDatastore"
  datacenter_name: "SDDC-Datacenter"
  datastore_iso_folder: "isos/agarciac"
  vm_folder_name: sandbox-pm2pn
  vm_folder: "/SDDC-Datacenter/vm/Workloads/sandbox-pm2pn"
  cluster_name: "Cluster-1"
  network_name:  segment-sandbox-pm2pn
  hwversion: 14
vm_definition:
  - hostname: master0.pm2pn.dynamic.opentlc.com
    disks:
      - size_gb: 120
        type: thin
        datastore: WorkloadDatastore
    ram: 32768
    cpu: 8
  - hostname: master1.pm2pn.dynamic.opentlc.com
    disks:
      - size_gb: 120
        type: thin
        datastore: WorkloadDatastore
    ram: 32768
    cpu: 8
  - hostname: master2.pm2pn.dynamic.opentlc.com
    disks:
      - size_gb: 120
        type: thin
        datastore: WorkloadDatastore
    ram: 32768
    cpu: 8
  - hostname: worker0.pm2pn.dynamic.opentlc.com
    disks:
      - size_gb: 120
        type: thin
        datastore: WorkloadDatastore
      - size_gb: 200
        type: thin
        datastore: WorkloadDatastore
    ram: 32768
    cpu: 8
  - hostname: worker1.pm2pn.dynamic.opentlc.com
    disks:
      - size_gb: 120
        type: thin
        datastore: WorkloadDatastore
      - size_gb: 200
        type: thin
        datastore: WorkloadDatastore
    ram: 32768
    cpu: 8
  - hostname: worker2.pm2pn.dynamic.opentlc.com
    disks:
      - size_gb: 120
        type: thin
        datastore: WorkloadDatastore
      - size_gb: 200
        type: thin
        datastore: WorkloadDatastore
    ram: 32768
    cpu: 8
hosts_definition:
  - hostname: master0.pm2pn.dynamic.opentlc.com
    role: master
    interfaces:
      - name: eth0
        macAddress: "{{ master0_mac }}"
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: "{{ master0_mac }}"
          ipv4:
            enabled: true
            address:
              - ip: 192.168.20.80
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.2.192.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.20.1
            next-hop-interface: eth0
            table-id: 254
  - hostname: master1.pm2pn.dynamic.opentlc.com
    role: master
    interfaces:
      - name: eth0
        macAddress: "{{ master1_mac }}"
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: "{{ master1_mac }}"
          ipv4:
            enabled: true
            address:
              - ip: 192.168.20.81
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.2.192.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.20.1
            next-hop-interface: eth0
            table-id: 254
  - hostname: master2.pm2pn.dynamic.opentlc.com
    role: master
    interfaces:
      - name: eth0
        macAddress: "{{ master2_mac }}"
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: "{{ master2_mac }}"
          ipv4:
            enabled: true
            address:
              - ip: 192.168.20.82
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.2.192.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.20.1
            next-hop-interface: eth0
            table-id: 254
  - hostname: worker0.pm2pn.dynamic.opentlc.com
    role: worker
    interfaces:
      - name: eth0
        macAddress: "{{ worker0_mac }}"
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: "{{ worker0_mac }}"
          ipv4:
            enabled: true
            address:
              - ip: 192.168.20.83
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.2.192.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.20.1
            next-hop-interface: eth0
            table-id: 254
  - hostname: worker1.pm2pn.dynamic.opentlc.com
    role: worker
    interfaces:
      - name: eth0
        macAddress: "{{ worker1_mac }}"
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: "{{ worker1_mac }}"
          ipv4:
            enabled: true
            address:
              - ip: 192.168.20.84
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.2.192.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.20.1
            next-hop-interface: eth0
            table-id: 254
  - hostname: worker2.pm2pn.dynamic.opentlc.com
    role: worker
    interfaces:
      - name: eth0
        macAddress: "{{ worker2_mac }}"
    rootDeviceHints:
      deviceName: /dev/sda
    networkConfig:
      interfaces:
        - name: eth0
          type: ethernet
          state: up
          mac-address: "{{ worker2_mac }}"
          ipv4:
            enabled: true
            address:
              - ip: 192.168.20.85
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.2.192.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.20.1
            next-hop-interface: eth0
            table-id: 254
...
