---
# tasks file for create-agent-iso
- name: Generate OpenShift Agent ISO
  ansible.builtin.shell:
    cmd: /usr/local/bin/openshift-install --log-level debug --dir ./ agent create image
    chdir: "{{ ocp_install_assets_dir }}"

- name: Set fact - agent ISO destination
  ansible.builtin.set_fact:
    agent_iso_dir: "{{ ocp_install_dir }}"
  when: (agent_iso_dir is undefined) or (agent_iso_dir == "")

- name: Generate OpenShift Agent ISO
  ansible.builtin.shell:
    cmd: /usr/bin/cp "./{{ ocp_install_assets_dir }}/{{ agent_iso_name }}" "{{ agent_iso_dir }}"
