---
- name: Install OpenShift
  hosts: localhost
  connection: local
  # Gather facts is required, otherwise this will fail.
  gather_facts: yes
  vars_files:
    - vars/cluster.yml
    - vars/vault.yml
    - vars/vsphere.yml

  pre_tasks:

    - name: Create VM to get MACs
      ansible.builtin.include_role:
        name: install-vsphere
        tasks_from: create_vm

  roles:

  - role: create-agent-iso
    tags:
    - iso

  - role: install-vsphere
    tags:
    - vsphere
...
