---
- name: OpenShift post-installation tasks
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/postinstall.yml

  roles:

  - role: postinstall_openshift
    tags:
    - postinstall
...
